name: Deploy to VPS

# This workflow triggers on every push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          # The script to run on the server
          script: |
            # Navigate to the application directory
            cd ~/smd/backend

            # Pull the latest changes from the main branch
            git pull origin main

            # Activate the virtual environment and install dependencies
            source venv/bin/activate
            pip install -r requirements.txt

            # The user needs passwordless sudo for this command
            sudo systemctl restart smd_api
            sudo systemctl restart smd_celery_worker
